// Auto-generated by scripts/generate-voice-demos.mjs
const VOICE_DEMO_FILES: Record<string, string> = {
  "Skylar": "/demos/skylar.mp3",
  "Katie": "/demos/katie.mp3",
  "Julia": "/demos/julia.mp3",
  "Ella": "/demos/ella.mp3",
  "Rachel": "/demos/rachel.mp3",
  "Grace": "/demos/grace.mp3",
  "Lauren": "/demos/lauren.mp3",
  "Michelle": "/demos/michelle.mp3",
  "Jessica": "/demos/jessica.mp3",
  "Caroline": "/demos/caroline.mp3",
  "Jameson": "/demos/jameson.mp3",
  "Theo": "/demos/theo.mp3",
  "Parker": "/demos/parker.mp3",
  "Austin": "/demos/austin.mp3",
  "Daniel": "/demos/daniel.mp3",
  "Zander": "/demos/zander.mp3",
  "Rowan": "/demos/rowan.mp3",
  "Gemma": "/demos/gemma.mp3",
  "Archie": "/demos/archie.mp3"
};
export default VOICE_DEMO_FILES;
